apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphaspnet-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graphaspnet-svc
  template:
    metadata:
      name: graphaspnet-svc
      labels:
        app: graphaspnet-svc
    spec:
      containers:
        - name: graphaspnet-svc
          image: graphaspnet-svc:latest
          imagePullPolicy: Never
          env:
            - name: ApplicationSettings__Neo4jConnection
              value: neo4j://my-neo4j-release:7687
            - name: ApplicationSettings__Neo4jUser
              value: neo4j
            - name: ApplicationSettings__Neo4jPassword
              value: neo4jpwd
            - name: ApplicationSettings__Neo4jDatabase
              value: neo4j
            - name: ApplicationName
              value: GraphDatabase, Neo4j - API
---
apiVersion: v1
kind: Service
metadata:
  name: graphaspnet-clusterip
spec:
  type: ClusterIP
  selector:
    app: graphaspnet-svc
  ports:
    - port: 8080
      targetPort: 8080